<?php
return array (
    "Directory",
    "stdClass",
    "__PHP_Incomplete_Class",
    "Exception",
    "exception",
    "ErrorException",
    "php_user_filter",
    "Closure",
    "Generator",
    "ArithmeticError",
    "AssertionError",
    "DivisionByZeroError",
    "Error",
    "Throwable",
    "ParseError",
    "TypeError",
    "mysqli",
    "Qrequest",
    "ArrayAccess", 
    "IteratorAggregate",
    "Countable",
    "ArrayIterator"
);
?>
